# Generated by Django 6.0.5 on 2026-06-24 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_product_features'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('in_app', models.BooleanField(default=True, help_text='Show in-app notification bell')),
                ('push', models.BooleanField(default=True, help_text='Send Web Push to subscribed devices')),
                ('sms', models.BooleanField(default=False, help_text='Send SMS (requires Pro/Enterprise plan)')),
                ('quiz_result_push', models.BooleanField(blank=True, default=None, null=True)),
                ('certificate_push', models.BooleanField(blank=True, default=None, null=True)),
                ('forum_push', models.BooleanField(blank=True, default=None, null=True)),
                ('announcement_sms', models.BooleanField(blank=True, default=None, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preferences',
            },
        ),
    ]
