# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_notification_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(
                choices=[
                    ('new_content', 'New Content'),
                    ('quiz_result', 'Quiz Result'),
                    ('certificate', 'Certificate'),
                    ('announcement', 'Announcement'),
                    ('forum', 'Forum'),
                    ('event_reminder', 'Event reminder'),
                    ('event_registration', 'Event registration'),
                ],
                max_length=30,
            ),
        ),
    ]
