# Generated by Django 6.0.5

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        ('tenants', '0006_grade_a_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicNews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('body', models.TextField()),
                ('body_ar', models.TextField(blank=True)),
                ('topic', models.CharField(
                    choices=[
                        ('announcement', 'Government announcement'),
                        ('education_update', 'Civic education update'),
                        ('election', 'Election information'),
                        ('law_policy', 'New laws and policies'),
                        ('awareness', 'Public awareness campaign'),
                    ],
                    db_index=True,
                    max_length=32,
                )),
                ('claim_type', models.CharField(
                    choices=[
                        ('verified_fact', 'Verified fact'),
                        ('educational', 'Educational explanation'),
                        ('opinion', 'Opinion'),
                        ('unverified', 'Unverified information'),
                    ],
                    db_index=True,
                    default='educational',
                    help_text='Never treat a missing label as a verified fact.',
                    max_length=32,
                )),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Draft'),
                        ('published', 'Published'),
                        ('archived', 'Archived'),
                    ],
                    db_index=True,
                    default='draft',
                    max_length=20,
                )),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='civic_news_created',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('organization', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)ss',
                    to='tenants.organization',
                )),
            ],
            options={
                'verbose_name': 'civic news item',
                'verbose_name_plural': 'civic news',
                'db_table': 'civic_news',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
    ]
