# Generated by Django 6.0.7

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0002_civicnews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuspiciousContentReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(
                    choices=[
                        ('whatsapp', 'WhatsApp or messaging app'),
                        ('facebook', 'Facebook or other social page'),
                        ('website', 'Website'),
                        ('radio', 'Radio or TV'),
                        ('other', 'Other'),
                    ],
                    db_index=True,
                    max_length=32,
                )),
                ('description', models.TextField(
                    help_text='Why the content looks suspicious. Do not paste the full rumour to spread it.',
                )),
                ('source_url', models.CharField(blank=True, default='', max_length=500)),
                ('reporter_contact', models.EmailField(blank=True, default='', max_length=254)),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('reviewed', 'Reviewed'),
                        ('dismissed', 'Dismissed'),
                    ],
                    db_index=True,
                    default='pending',
                    max_length=20,
                )),
                ('moderator_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reporter', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='suspicious_content_reports',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('reviewed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='suspicious_reports_reviewed',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('organization', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)ss',
                    to='tenants.organization',
                )),
            ],
            options={
                'db_table': 'suspicious_content_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
