# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0003_suspiciouscontentreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='kind',
            field=models.CharField(
                choices=[('educational', 'Educational'), ('community', 'Community')],
                db_index=True,
                default='community',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='region',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='pollvote',
            name='age_band',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
