# Generated by Django 6.0.7

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0004_poll_kind_vote_demographics'),
        ('tenants', '0006_grade_a_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CivicEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('location_ar', models.CharField(blank=True, max_length=255)),
                ('kind', models.CharField(
                    choices=[
                        ('election', 'Election'),
                        ('public_consultation', 'Public consultation'),
                        ('community_meeting', 'Community meeting'),
                        ('workshop', 'Civic education workshop'),
                        ('national_holiday', 'National holiday'),
                        ('public_hearing', 'Public hearing'),
                    ],
                    db_index=True,
                    max_length=32,
                )),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('is_all_day', models.BooleanField(default=False)),
                ('status', models.CharField(
                    choices=[
                        ('draft', 'Draft'),
                        ('published', 'Published'),
                        ('cancelled', 'Cancelled'),
                    ],
                    db_index=True,
                    default='draft',
                    max_length=20,
                )),
                ('allows_registration', models.BooleanField(default=True)),
                ('capacity', models.PositiveIntegerField(blank=True, null=True)),
                ('source_name', models.CharField(blank=True, max_length=255)),
                ('source_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='civic_events_created',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('organization', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)ss',
                    to='tenants.organization',
                )),
            ],
            options={
                'verbose_name': 'civic event',
                'verbose_name_plural': 'civic events',
                'db_table': 'civic_events',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='EventSignup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_registered', models.BooleanField(default=False)),
                ('reminder_enabled', models.BooleanField(db_index=True, default=False)),
                ('reminder_sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='signups',
                    to='engagement.civicevent',
                )),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='event_signups',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('organization', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)ss',
                    to='tenants.organization',
                )),
            ],
            options={
                'db_table': 'event_signups',
                'unique_together': {('organization', 'event', 'user')},
            },
        ),
        migrations.AddIndex(
            model_name='eventsignup',
            index=models.Index(fields=['reminder_enabled', 'reminder_sent_at'], name='event_signu_reminde_f955c1_idx'),
        ),
    ]
