# Generated by Django 6.0.5 on 2026-07-20 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0006_enterprise_gov_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='document_label',
            field=models.CharField(blank=True, default='', help_text='Institutional label for controlled documents (e.g. Transitional Constitution).', max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='is_controlled_document',
            field=models.BooleanField(default=False, help_text='Controlled institutional PDF — version/label required; deletion restricted.'),
        ),
        migrations.AddField(
            model_name='category',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Official curriculum category — cannot be deleted; slug/name locked for non-owners.'),
        ),
    ]
