# Generated by Django 6.0.7 on 2026-07-21 05:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0007_enterprise_gaps'),
        ('tenants', '0006_grade_a_enterprise'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True)),
                ('media_type', models.CharField(choices=[('audio', 'Audio'), ('video', 'Video')], db_index=True, max_length=10)),
                ('source', models.CharField(choices=[('upload', 'Upload'), ('external', 'External URL')], default='external', max_length=10)),
                ('file_url', models.CharField(blank=True, default='', max_length=2048)),
                ('external_url', models.URLField(blank=True, default='')),
                ('mime_type', models.CharField(blank=True, default='', max_length=100)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('thumbnail_url', models.URLField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_assets', to='learning.category')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='tenants.organization')),
            ],
            options={
                'db_table': 'media_assets',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='article',
            name='audio_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_as_audio', to='learning.mediaasset'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles_as_video', to='learning.mediaasset'),
        ),
    ]
