# Generated by Django 6.0.5 on 2026-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning', '0009_learning_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='tutor_index_text',
            field=models.TextField(blank=True, default='', help_text='Pre-indexed body + PDF text for AI tutor retrieval.'),
        ),
        migrations.AddField(
            model_name='mediaasset',
            name='captions_url',
            field=models.URLField(blank=True, default='', help_text='WebVTT captions URL for audio/video accessibility.'),
        ),
    ]
