# Generated by Django 6.0.5 on 2026-06-21 10:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('email_verified', 'Email Verified'), ('password_reset', 'Password Reset'), ('user_suspended', 'User Suspended'), ('article_created', 'Article Created'), ('article_updated', 'Article Updated'), ('article_deleted', 'Article Deleted'), ('quiz_created', 'Quiz Created'), ('quiz_attempt', 'Quiz Attempt'), ('certificate_issued', 'Certificate Issued'), ('topic_created', 'Topic Created'), ('comment_created', 'Comment Created'), ('content_moderated', 'Content Moderated'), ('admin_action', 'Admin Action')], db_index=True, max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'activity_logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
