# Generated by Django 6.0.5 on 2026-06-23 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('tenants', '0002_organization_invites'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='tenants.organization'),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('email_verified', 'Email Verified'), ('password_reset', 'Password Reset'), ('user_suspended', 'User Suspended'), ('user_unsuspended', 'User Unsuspended'), ('article_created', 'Article Created'), ('article_updated', 'Article Updated'), ('article_deleted', 'Article Deleted'), ('quiz_created', 'Quiz Created'), ('quiz_attempt', 'Quiz Attempt'), ('certificate_issued', 'Certificate Issued'), ('topic_created', 'Topic Created'), ('comment_created', 'Comment Created'), ('content_moderated', 'Content Moderated'), ('admin_action', 'Admin Action')], db_index=True, max_length=50),
        ),
    ]
