# Generated by Django 6.0.5 on 2026-06-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_activitylog_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('email_verified', 'Email Verified'), ('password_reset', 'Password Reset'), ('user_suspended', 'User Suspended'), ('user_unsuspended', 'User Unsuspended'), ('user_role_changed', 'User Role Changed'), ('article_created', 'Article Created'), ('article_updated', 'Article Updated'), ('article_deleted', 'Article Deleted'), ('quiz_created', 'Quiz Created'), ('quiz_attempt', 'Quiz Attempt'), ('certificate_issued', 'Certificate Issued'), ('topic_created', 'Topic Created'), ('comment_created', 'Comment Created'), ('content_moderated', 'Content Moderated'), ('admin_action', 'Admin Action')], db_index=True, max_length=50),
        ),
    ]
