# Generated by Django 6.0.5 on 2026-07-20 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_alter_activitylog_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='user_agent',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='activity_type',
            field=models.CharField(choices=[('user_registered', 'User Registered'), ('user_login', 'User Login'), ('user_logout', 'User Logout'), ('user_login_failed', 'User Login Failed'), ('email_verified', 'Email Verified'), ('password_reset', 'Password Reset'), ('user_suspended', 'User Suspended'), ('user_unsuspended', 'User Unsuspended'), ('user_role_changed', 'User Role Changed'), ('user_deactivated', 'User Deactivated'), ('data_exported', 'Data Exported'), ('member_invited', 'Member Invited'), ('member_removed', 'Member Removed'), ('member_role_changed', 'Member Role Changed'), ('org_settings_changed', 'Organization Settings Changed'), ('sso_configured', 'SSO Configured'), ('sso_login', 'SSO Login'), ('bulk_import', 'Bulk Import'), ('article_created', 'Article Created'), ('article_updated', 'Article Updated'), ('article_deleted', 'Article Deleted'), ('article_submitted', 'Article Submitted for Review'), ('article_approved', 'Article Approved'), ('article_rejected', 'Article Rejected'), ('quiz_created', 'Quiz Created'), ('quiz_attempt', 'Quiz Attempt'), ('certificate_issued', 'Certificate Issued'), ('topic_created', 'Topic Created'), ('comment_created', 'Comment Created'), ('content_moderated', 'Content Moderated'), ('admin_action', 'Admin Action'), ('org_activated', 'Organization Activated'), ('org_deactivated', 'Organization Deactivated')], db_index=True, max_length=50),
        ),
    ]
