# Generated by Django 6.0.5 on 2026-06-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_certificate_organization_quiz_organization_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='options_ar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
