# Generated by Django 6.0.5 on 2026-07-20 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userprofile_mfa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='session_epoch',
            field=models.PositiveIntegerField(default=0, help_text='Incremented to revoke all outstanding JWTs for this user.'),
        ),
    ]
