# Generated by Django 6.0.5 on 2026-07-25 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_grade_a_enterprise'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xp_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
