# Generated by Django 6.0.7

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_userprofile_xp_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Prefer not to say / not set'),
                    ('central_equatoria', 'Central Equatoria'),
                    ('eastern_equatoria', 'Eastern Equatoria'),
                    ('western_equatoria', 'Western Equatoria'),
                    ('jonglei', 'Jonglei'),
                    ('unity', 'Unity'),
                    ('upper_nile', 'Upper Nile'),
                    ('lakes', 'Lakes'),
                    ('warrap', 'Warrap'),
                    ('northern_bahr_el_ghazal', 'Northern Bahr el Ghazal'),
                    ('western_bahr_el_ghazal', 'Western Bahr el Ghazal'),
                    ('other', 'Other or outside South Sudan'),
                    ('prefer_not', 'Prefer not to say'),
                ],
                default='',
                max_length=40,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='age_band',
            field=models.CharField(
                blank=True,
                choices=[
                    ('', 'Prefer not to say / not set'),
                    ('under_18', 'Under 18'),
                    ('18_24', '18–24'),
                    ('25_34', '25–34'),
                    ('35_49', '35–49'),
                    ('50_plus', '50 and over'),
                    ('prefer_not', 'Prefer not to say'),
                ],
                default='',
                max_length=20,
            ),
        ),
    ]
