# Generated by Django 6.0.5 on 2026-06-23 05:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learning', '0003_article_organization_category_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorChat',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=64)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=10)),
                ('message', models.TextField()),
                ('tokens_used', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutor_chats', to='learning.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_chats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tutor_chats',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_id'], name='tutor_chats_session_6f9d77_idx'), models.Index(fields=['user', 'created_at'], name='tutor_chats_user_id_981b03_idx')],
            },
        ),
    ]
