# Generated by Django 6.0.5 on 2026-06-24 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_migrate_primary_color_to_green'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='primary_color',
            field=models.CharField(default='#059669', max_length=7),
        ),
    ]
