# Generated by Django 6.0.5 on 2026-07-20 20:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_organization_primary_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='audit_retention_days',
            field=models.PositiveIntegerField(default=365, help_text='Days to retain activity logs for this organization (0 = keep forever).'),
        ),
        migrations.AddField(
            model_name='organization',
            name='force_mfa_for_admins',
            field=models.BooleanField(default=True, help_text='Require MFA for organization owners and admins.'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('content_manager', 'Content manager'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='organizationinvite',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('content_manager', 'Content manager'), ('moderator', 'Moderator'), ('member', 'Member')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenants.organization')),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['name'],
                'unique_together': {('organization', 'name'), ('organization', 'slug')},
            },
        ),
        migrations.AddField(
            model_name='membership',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='tenants.department'),
        ),
        migrations.AddField(
            model_name='organizationinvite',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites', to='tenants.department'),
        ),
        migrations.CreateModel(
            name='OrganizationSsoConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('enabled', models.BooleanField(default=False)),
                ('issuer', models.URLField(blank=True)),
                ('client_id', models.CharField(blank=True, max_length=255)),
                ('client_secret', models.CharField(blank=True, max_length=512)),
                ('scopes', models.CharField(blank=True, default='openid email profile', max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sso_config', to='tenants.organization')),
            ],
            options={
                'db_table': 'organization_sso_configs',
            },
        ),
    ]
