# Generated by Django 6.0.7

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_discussioncomment_organization_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='discussiontopic',
            name='kind',
            field=models.CharField(
                choices=[('discussion', 'Discussion'), ('question', 'Question')],
                db_index=True,
                default='discussion',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='board',
            field=models.CharField(
                choices=[
                    ('general', 'general'),
                    ('constitution', 'constitution'),
                    ('elections', 'elections'),
                    ('rights', 'rights'),
                    ('governance', 'governance'),
                    ('media', 'media'),
                    ('peace', 'peace'),
                ],
                db_index=True,
                default='general',
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussioncomment',
            name='is_expert',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='discussiontopic',
            name='accepted_answer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='+',
                to='forum.discussioncomment',
            ),
        ),
        migrations.CreateModel(
            name='ForumReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('target_type', models.CharField(
                    choices=[('topic', 'Topic'), ('comment', 'Comment')],
                    db_index=True,
                    max_length=16,
                )),
                ('reason', models.CharField(
                    choices=[
                        ('hate_speech', 'hate_speech'),
                        ('harassment', 'harassment'),
                        ('misinformation', 'misinformation'),
                        ('political_manipulation', 'political_manipulation'),
                        ('other', 'other'),
                    ],
                    db_index=True,
                    max_length=40,
                )),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(
                    choices=[
                        ('pending', 'Pending'),
                        ('reviewed', 'Reviewed'),
                        ('dismissed', 'Dismissed'),
                    ],
                    db_index=True,
                    default='pending',
                    max_length=20,
                )),
                ('moderator_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reports',
                    to='forum.discussioncomment',
                )),
                ('organization', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='%(class)ss',
                    to='tenants.organization',
                )),
                ('reporter', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='forum_reports',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('reviewed_by', models.ForeignKey(
                    blank=True,
                    null=True,
                    on_delete=django.db.models.deletion.SET_NULL,
                    related_name='forum_reports_reviewed',
                    to=settings.AUTH_USER_MODEL,
                )),
                ('topic', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE,
                    related_name='reports',
                    to='forum.discussiontopic',
                )),
            ],
            options={
                'db_table': 'forum_reports',
                'ordering': ['-created_at'],
            },
        ),
    ]
