"""Locust load test for the CivicHub API.

Simulates the read-heavy traffic the SRS targets (50k registered users,
10k concurrent). Each simulated user registers once, logs in, then loops
through realistic browsing/learning actions.

Usage (web UI):
    locust -f loadtest/locustfile.py --host http://localhost:8000

Usage (headless, ramp to 10k users):
    locust -f loadtest/locustfile.py --host http://localhost:8000 \
        --users 10000 --spawn-rate 200 --run-time 10m --headless

Notes:
    * Run against a production-like build (DEBUG=False, gunicorn, Postgres,
      Redis + a Celery worker) for meaningful numbers. The Django dev server
      is single-threaded and will not reflect real capacity.
    * Generating 10k concurrent users typically needs Locust distributed mode
      (one --master + several --worker processes, often across machines).
"""

import random
import uuid

from locust import HttpUser, between, task

PASSWORD = "LoadTest123!"


class CivicUser(HttpUser):
    wait_time = between(1, 5)

    def on_start(self):
        """Register and log in a unique user, then cache the auth header."""
        self.token = None
        email = f"load_{uuid.uuid4().hex[:12]}@loadtest.local"

        self.client.post(
            "/api/auth/register/",
            json={
                "email": email,
                "first_name": "Load",
                "last_name": "Test",
                "password": PASSWORD,
                "password_confirm": PASSWORD,
            },
            name="/api/auth/register/",
        )

        resp = self.client.post(
            "/api/auth/login/",
            json={"email": email, "password": PASSWORD},
            name="/api/auth/login/",
        )
        if resp.status_code == 200:
            self.token = resp.json().get("access")

    @property
    def auth_headers(self):
        return {"Authorization": f"Bearer {self.token}"} if self.token else {}

    @task(10)
    def browse_articles(self):
        self.client.get("/api/articles/", name="/api/articles/")

    @task(5)
    def browse_articles_arabic(self):
        self.client.get("/api/articles/?lang=ar", name="/api/articles/?lang=ar")

    @task(4)
    def list_categories(self):
        self.client.get("/api/categories/", name="/api/categories/")

    @task(6)
    def list_quizzes(self):
        self.client.get(
            "/api/quizzes/", headers=self.auth_headers, name="/api/quizzes/"
        )

    @task(5)
    def browse_topics(self):
        self.client.get("/api/topics/", name="/api/topics/")

    @task(3)
    def check_notifications(self):
        if self.token:
            self.client.get(
                "/api/notifications/",
                headers=self.auth_headers,
                name="/api/notifications/",
            )

    @task(2)
    def view_profile(self):
        if self.token:
            self.client.get(
                "/api/users/profile/",
                headers=self.auth_headers,
                name="/api/users/profile/",
            )

    @task(1)
    def create_topic(self):
        if not self.token:
            return
        self.client.post(
            "/api/topics/",
            json={
                "title": f"Load discussion {random.randint(1, 10_000)}",
                "content": "Generated by load test.",
            },
            headers=self.auth_headers,
            name="/api/topics/ [create]",
        )
