import i18n from '../i18n';
import { normalizeLanguage } from '../i18n/languages';
import type { Id, QueryParams } from '../types/api';

function contentLangKey() {
  return normalizeLanguage(i18n.language);
}

export const queryKeys = {
  categories: () => ['categories', contentLangKey()] as const,
  articles: (params?: QueryParams) => ['articles', contentLangKey(), params] as const,
  article: (id?: Id) => ['article', contentLangKey(), id] as const,
  forumTopics: (params?: QueryParams) => ['forum', 'topics', params] as const,
  forumTopic: (id?: Id) => ['forum', 'topic', id] as const,
  notifications: (params?: QueryParams) => ['notifications', params] as const,
  notificationsUnread: ['notifications', 'unread'] as const,
  quizzes: (params?: QueryParams) => ['quizzes', contentLangKey(), params] as const,
  quiz: (id?: Id) => ['quiz', contentLangKey(), id] as const,
  quizResults: (params?: QueryParams) => ['quiz-results', contentLangKey(), params] as const,
  certificates: (params?: QueryParams) => ['certificates', contentLangKey(), params] as const,
  organization: ['organization'] as const,
  orgMembers: ['organization', 'members'] as const,
  myOrganizations: ['organization', 'mine'] as const,
  billing: ['billing'] as const,
  plans: ['plans'] as const,
  orgDashboard: (filters?: QueryParams) => ['dashboard', filters] as const,
  orgProgress: (filters?: QueryParams) => ['dashboard', 'progress', filters] as const,
  myLearning: ['dashboard', 'me'] as const,
  articlesManage: ['articles', 'manage'] as const,
  categoriesManage: ['categories', 'manage'] as const,
  quizzesManage: ['quizzes', 'manage'] as const,
  media: (params?: QueryParams) => ['media', contentLangKey(), params] as const,
  mediaItem: (id?: Id) => ['media', contentLangKey(), id] as const,
  mediaManage: ['media', 'manage'] as const,
  quizEdit: (id?: Id) => ['quizzes', 'edit', id] as const,
  tutorUsage: ['tutor', 'usage'] as const,
  tutorHistory: ['tutor', 'history'] as const,
  search: (q: string) => ['search', q] as const,
  gamificationMe: ['gamification', 'me'] as const,
  leaderboard: ['gamification', 'leaderboard'] as const,
  recommendations: ['learning', 'recommendations'] as const,
  civicMap: ['maps', 'civic'] as const,
  bookmarks: (params?: QueryParams) => (params ? (['bookmarks', params] as const) : (['bookmarks'] as const)),
  news: (params?: QueryParams) => ['news', contentLangKey(), params] as const,
  newsItem: (id?: Id) => ['news', contentLangKey(), id] as const,
  newsManage: ['news', 'manage'] as const,
  events: (params?: QueryParams) => ['events', contentLangKey(), params] as const,
  eventItem: (id?: Id) => ['events', contentLangKey(), id] as const,
  eventsManage: ['events', 'manage'] as const,
  awareness: () => ['awareness', contentLangKey()] as const,
  awarenessReports: ['awareness', 'reports'] as const,
  engagementPolls: (kind?: string) => ['engagement', 'polls', kind || 'all'] as const,
  engagementPetitions: ['engagement', 'petitions'] as const,
  engagementCampaigns: ['engagement', 'campaigns'] as const,
  engagementManage: (kind: string) => ['engagement', 'manage', kind] as const,
  courses: () => ['courses', contentLangKey()] as const,
  course: (id?: Id) => ['course', contentLangKey(), id] as const,
  coursesManage: ['courses', 'manage'] as const,
  adminOverview: ['admin', 'overview'] as const,
  adminQuizzes: ['admin', 'quizzes'] as const,
  adminForum: ['admin', 'forum'] as const,
  adminPending: ['admin', 'pending'] as const,
};
